HW10/HW10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
    
]

HW10/quotes/urls.py
from django.urls import path
from . import views
from quotes.views import author_quotes, list_author, tag, tag_detail


app_name = 'quotes'
urlpatterns = [
    path("", views.main, name='main'),
    path("<int:page>", views.main, name='root_paginate'),
    path("add_author", views.add_author, name="add_author"),
    path("add_quote", views.add_quote, name="add_quote"),
    path('tag/', views.tag, name='tag'),
    path('author/<str:author_name>/',list_author, name='author'),
    path('tag/<str:tag_name>/', tag_detail, name='tag_detail'),
    ]

HW10/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

HW10/quotes/models.py
from django.db import models
from django.contrib.auth.models import User




class Author(models.Model):
    fullname = models.CharField(max_length=50)
    date_born= models.CharField(max_length=50)
    location_born= models.CharField(max_length=150)
    bio= models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name'], name='tag of username')
         ]

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote
  

HW10/quotes/forms.py
from django.forms import ModelForm, CharField,TextInput, DateField, DateInput, ModelChoiceField, Select, Textarea, ModelMultipleChoiceField, SelectMultiple
from .models import Author, Quote, Tag


class QuoteForm(ModelForm):
    quote = CharField(widget=Textarea(attrs={"class": "form-control", "rows": "5"}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), widget=Select(attrs={"class": "form-select"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by("name"),widget=SelectMultiple(attrs={"size": "12",}))

    class Meta:
        model = Quote
        fields = ['author', 'quote', 'tags', ]

class TagForm(ModelForm):
    name = CharField(max_length=30, min_length=2, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tag
        fields = ['name', ]

class AuthorForm(ModelForm):
    fullname = CharField(max_length=40, min_length=2, widget=TextInput(attrs={"class": "form-control"}))
    born_date  = DateField(widget=DateInput(attrs={"class": "form-control"})) 
    born_location = CharField(max_length=150,widget=TextInput(attrs={"class": "form-control",}),)
    description = CharField(max_length=40, min_length=30, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date',"born_location", 'bio',  ]

HW10/quotes/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Quote, Author
from django.db.models import Count

from .utils import get_mongodb

def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'paginator': paginator})

def list_author(request, author_name):
    author = get_object_or_404(Author, fullname=author_name)
    return render(request, 'author.html', {'author': author})

def tag_detail(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    quotes = Quote.objects.filter(tags=tag).order_by("-created_at")
    return render(request, 'quotes/tag_detail.html', {'tag': tag, 'quotes': quotes})


def author_quotes(request, author_name):
    author = get_object_or_404(Author, name=author_name)
    quotes = Quote.objects.filter(authors=author)
    return render(request, 'quotes/author_quote.html', {'author': author, 'quotes': quotes})

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.author=request.user
            tag.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/tag.html', {'form': form})

    return render(request, 'quotes/tag.html', {'form': TagForm()})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = QuoteForm()

    return render(request, 'quotes/quote.html', {'form': form})

@login_required
def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id, author=request.user)
    return render(request, 'quotes/detail.html', {"quote": quote})


@login_required
def set_quote(request, quote_id):
    Quote.objects.filter(pk=quote_id, author=request.user).update(done=True)
    return redirect(to='quotes:main')


@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id, author=request.user).delete()
    return redirect(to='quotes:main')


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            return redirect('/')
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})

@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect('/')
    else:
        form = TagForm()
    return render(request, 'quotes/add_tag.html', {'form': form})

HW10/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'quotes:add_author' %}">
        {% csrf_token %}
        <div style="padding: 10px">
            <label>Enter the author fullname:</label>
                {{form.fullname}}        
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div style="padding: 10px">
            <label>Enter the author born date:</label>
                {{form.born_date}}
            <span>{{ form.errors.born_date }}</span>
        </div>
        <div style="padding: 10px">
            <label>Enter the author born location:</label>
                {{form.born_location}}
            <span>{{ form.errors.born_location }}</span>
        </div>
        <div style="padding: 10px">
            <label>Enter the author biografia:</label>
                {{form.description}}
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
{% endblock %}

HW10/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'quotes:add_tag' %}">
        {% csrf_token %}
        <div style="padding: 10px">
            <label>Enter the tag name:</label>
                {{form.name}}        
            <span>{{ form.errors.name }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
{% endblock %}

HW10/quotes/templates/quotes/author copy.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container mt-3">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ author.fullname }}</h5>
            <p class="card-text">{{ quote.text }}</p>
            <p class="card-text"><small class="text-muted">Author's Birth Date: {{ author.born_date }}</small></p>
            <p class="card-text"><small class="text-muted">Author's Bio: {{ author.description }}</small></p>
            <p class="card-text"><small class="text-muted">Author's Born Location: {{ author.born_location }}</small></p>
        </div>
    </div>
</div>

{% endblock %}

HW10/quotes/templates/quotes/author.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Quotes by {{ author.name }}</h1>
<ul>
    {% for quote in quotes %}
        <li>{{ quote.text }}</li>
        <a href="{% url 'author_quotes' author.name %}">{{ author.name }}</a>
        <li>No quotes found.</li>
        {% empty %}
    {% endfor %}
</ul>
{% endblock %}

HW10/quotes/templates/quotes/author_quotes.html
{% extends "quotes/base.html" %}

{% block title %}{{ tag.name }}{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1>{{ tag.name }}</h1>
        <h2>Quotes with this tag:</h2>
        {% for quote in quotes %}
            <h3>"{{ quote.quote }}"</h3>
            <p>Author: <a href="{% url 'quotes:author_detail' quote.author.pk %}">{{ quote.author.fullname }}</a></p>
        {% endfor %}
    </div>
{% endblock %}

HW10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}"
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a class="nav-link btn btn-success" href="{% url 'quotes:add_quote' %}">Add Quote</a>
                    <a class="nav-link btn btn-info" href="{% url 'quotes:add_author' %}">Add Author</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                </p>
            </div>
        </div>
    

        {% block content%} {% endblock%}
    

</div>
</body>
</html>

HW10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract_tags %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                
                {% endfor %}
                
            </div>
        </div>
        
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class='{% if not quotes.has_previous %} disabled {% endif %}'
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                
                
                <li class="next">
                    <a class='{% if not quotes.has_next %} disabled {% endif %}'
                    href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
                </li>
                
            </ul>
        </nav>
        </div>

</div>

{% endblock %}  

HW10/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote text:</label>
            {{form.quote}}        
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author fullname:</label>
            {{form.author}}
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label>Select the tag:</label>
            {{form.tags}}
        <span>{{ form.errors.tags }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

HW10/quotes/templates/quotes/tag_detail.html
{% extends "quotes/base.html" %}

{% block title %}{{ tag.name }}{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1>{{ tag.name }}</h1>
        <h2>Quotes with this tag:</h2>
        {% for quote in quotes %}
            <h3>"{{ quote.quote }}"</h3>
            <p>Author: <a href="{% url 'author_quotes' quote.author.name %}">{{ quote.author.name }}</a></p></p>
        {% endfor %}
    </div>
{% endblock %}